travis:
  secure:
    BINSTAR_TOKEN: PgyuKCCE8Dk8H4sHEUsSLoAf2xrrVeRpAAETZtoXbrRw5Yt3lifPQDg/FbdUEbBIhPFTgG86sYIwqHAdPOJ7z2B+/iRbbVM9EdroecJCsaeEaJsKN9vD2BSAKsn74OVD8FGLjTcnK0V8oZ8widZA/sUq7Hy3Rrfwvi9WFl/ixM1IcNWJ6clFUg5dVgVqKsdJETrsjW0G2DLYvR2wTDzcdvUc9HN7UooAl4Ek7x8BOmTJHFTNlk3fTxige57qf7XLpUZvAgw0Ts2+ZKM77nrYsWRAQyAX/yy5v09UAmMHkcn/gWNycdkt+Agl3n7tRNnLSOOqBAMEYjS+FbPtAE8Wp1BEYlVXceuVsXuNV8LpoFcDnh/IacJqGw5FyXv3kNmbtnz6bPaE4TUh0jpzdmwGCtxM5n6m+CRIDfXsWfPydbZ5sHdFjUXdC5S7Uk0gvpe4vhJqy1tUSaJOrxbxCVymqR+uL6pIZfltPSJikt91T6cymZ7Dr7tfEVJBbspxLtc0hfhcZmajlC01x8g7GzpDIjmQopAIrofzsw3E0Lqn/goWiSXDK+5LPCuTN9FWaKQUeZKNn0xGxHZdlCKyu59vAItYXbCtG8igyDJlrx5bJ0I/IXuneUyXzunpdRrJZQLBGNI110bFRER4ZcJAfH3iew8TFAI2zU1ZIYyQhMbQEzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
