travis:
  secure:
    BINSTAR_TOKEN: fJZMf9rWVpg3bizVX4Jn6Cnyyb6DXvtOyhBKaDe3PY3Hh43LyzZXpWkRiwqFwDvngfgH9QAaOaG/PjPRDan7ekx09eHjRVn5e6r2Uc3rSYfkomHDNEu3D5wvY+zzLvKNcHj7YRrfdgMS0It3+/HoIPzPMBs1YPEODI2JONzlNeYa7gVUzTkNx1hR1zc+jRgWuRJkklSUufhbuDmqZkUY+Zs9vm6GZdlHpZ+m0A5EMNgPNr45PNAMRgfwxA2m2Cnk3qwpK/6A3k8mKJjJFLke/noubMleBoN4mUMQLIfuygLjAukr/2xPLnJPnQZ1vyZW7ft/4Iygtw7Yb07FOxh/fU2DCFB0UzLKLd99st/AXhD/iB23hCpwf29nHhGl1CtcP/HG1XT8TgStu0HU0i/amq0GStfz2FfsLrddrqHilZ9mtJiLXKs+oAuo74WScihYdt8CJw6bTqPAKbwWJKbzy/KvQQvwNDYY/RrdSOQuCSXSQacU8W5zOkbfrB2te2ZR2BZaJ+NctcuguWDB+ZVw88itL9d1hRfQHzIPo4pK1EVaWBgOEyQMRd/EqLbbvGFOX0Gqx1uwk7fUxvsBqo77Qr3yDBi6quq9r4zScmbRM+i6o2y1UMYJ/+SzLK1eBwTis5io6XZgHrM+zYlFKRAC6PCGOEdiUVCMGNBi6/pxO0Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
