travis:
  secure:
    BINSTAR_TOKEN: R0aHLanIVIxUzV8wCtcU5BYXAUVYPRKeGdVajeVOr3P7F1l5/TRwoExtg/eGgZKJmBI4Gf669TEZPPITzErHjtoxn8h0i4DuOHDiTl3yf4+EYHqTJNCm0Qmze4yaJLvDTfUTbMil5HH3yBvWCSSICwu9GMn5zkPvl29GS5yki5sxYNw8wwCOP4kk5U8kpGE9PFh1hDQDFH9uK+MPPFGinYUKoDkmYzqeYVzYU/GAVdpcH52RF0u+yiKN3OeJt/MPd/K5vp2xcj6QGoXJbP8csR6y4SqdpT76WgMp8ZvCnuePAMBwm9vMJEeG/9NVAtIq+yFQ9ksH2uPKD0J/S4+OSryJpia4CAb7YRveNXwgPMblFrKlneG0u/vawis2Ti2XqwvEAPYe9tbCfxRAC/7Kid3tKvGLHf0qUuWrNSlw8X9PB1vtwpT8MUJjLzOejKfS0/AovMsAzrSdnEKv5gSLRRwzSgJTpLtYrlWeLfylPUdKPZmfm+Oobk2TDlMYq2su0jQL0t5czD2nlPNhFgbgcXincLm8RVbO5gqgNe87H47cqO7rNL4VLVq6kKDNRe4yl6aiEFhpQUgBU7Imi0q57Ix80DvCZOMRUq28V5px9B5FSw2OiODU1eBYgiegJVUvGIZ35DRNntDH4SSMKA/HPxw/dYxo3oPZ/EW/5F9dC5s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
